class ListMaster {
  static List<String> designations = [
    "Broker",
    "Branch Manager",
    "CEO",
    "CFO",
    "CTO",
    "Owner",
    "Software Developer/Engineer",
    "System Analyst",
    "Quality Assurance (QA) Engineer",
    "Technical Support Specialist",
    "IT Support Engineer",
    "Web Developer",
    "Database Administrator (Junior)",
    "Senior Software Engineer",
    "Project Manager",
    "Business Analyst",
    "UI/UX Designer",
    "DevOps Engineer",
    "Cloud Solutions Architect",
    "Data Scientist",
    "Network Administrator",
    "Cybersecurity Analyst",
    "Lead Software Engineer",
    "Solutions Architect",
    "IT Manager",
    "Product Manager",
    "Director of Technology",
    "Senior Data Scientist",
    "Head of IT Operations",
    "Chief Technology Officer (CTO)",
    "Chief Information Officer (CIO)",
    "AI/Machine Learning Engineer",
    "Blockchain Developer",
    "Cloud Engineer",
    "Infrastructure Engineer",
    "Mobile App Developer",
    "Business Intelligence Analyst",
    "Full Stack Developer",
    "Network Engineer",
    "Founder",
    "Co-Founder",
    "CEO (Chief Executive Officer)",
    "COO (Chief Operating Officer)",
    "Plant Manager",
    "Production Manager",
    "Operations Manager",
    "Quality Control Manager",
    "Maintenance Manager",
    "Production Supervisor",
    "Machine Operator",
    "Assembly Line Worker",
    "Quality Assurance Engineer",
    "Process Engineer",
    "Manufacturing Engineer",
    "Logistics Coordinator",
    "Inventory Manager",
    "Forklift Operator",
    "Supply Chain Manager",
    "Health & Safety Officer",
    "Maintenance Technician",
    "Tooling Engineer",
    "Financial Analyst",
    "Investment Banker",
    "Portfolio Manager",
    "Risk Manager",
    "Compliance Officer",
    "Financial Advisor",
    "Relationship Manager",
    "Wealth Manager",
    "Financial Planner",
    "Tax Advisor",
    "Chief Financial Officer (CFO)",
    "Credit Analyst",
    "Asset Manager",
    "Fund Manager",
    "Insurance Underwriter",
    "Loan Officer",
    "Financial Controller",
    "Trading Desk Manager",
    "Private Equity Analyst",
    "Client Service Manager",
    "Consultant",
    "Senior Consultant",
    "Associate Consultant",
    "Manager",
    "Senior Manager",
    "Principal Consultant",
    "Director",
    "Associate Director",
    "Partner",
    "Managing Director",
    "Vice President",
    "Senior Vice President",
    "Engagement Manager",
    "Business Analyst",
    "Senior Business Analyst",
    "Strategy Consultant",
    "Lead Consultant",
    "Client Relationship Manager",
    "Research Analyst",
    "CEO (Chief Executive Officer)",
    "COO (Chief Operating Officer)",
    "CFO (Chief Financial Officer)",
    "CMO (Chief Marketing Officer)",
    "CTO (Chief Technology Officer)",
    "Product Manager",
    "Marketing Manager",
    "Sales Manager",
    "Business Development Manager",
    "Customer Support Manager",
    "Operations Manager",
    "Logistics Manager",
    "Supply Chain Manager",
    "E-commerce Manager",
    "Data Analyst",
    "Content Manager",
    "SEO Specialist",
    "Social Media Manager",
    "UX/UI Designer",
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Inventory Manager",
    "Warehouse Manager",
    "Quality Assurance (QA) Tester",
    "Customer Service Representative",
    "Content Writer",
    "Digital Marketing Specialist",
    "Graphic Designer",
    "CEO (Chief Executive Officer)",
    "COO (Chief Operating Officer)",
    "CFO (Chief Financial Officer)",
    "CMO (Chief Medical Officer)",
    "CIO (Chief Information Officer)",
    "Clinical Director",
    "Medical Director",
    "Nurse Manager",
    "Healthcare Administrator",
    "Patient Care Coordinator",
    "Pharmacist",
    "Clinical Research Coordinator",
    "Medical Records Manager",
    "Health IT Specialist",
    "Compliance Officer",
    "Healthcare Marketing Director",
    "Operations Manager",
    "Registered Nurse (RN)",
    "Physician",
    "Physical Therapist",
    "CEO (Chief Executive Officer)",
    "COO (Chief Operating Officer)",
    "CFO (Chief Financial Officer)",
    "Director of Education",
    "Curriculum Developer",
    "Instructional Designer",
    "Educational Consultant",
    "Learning and Development Manager",
    "Content Specialist",
    "E-Learning Specialist",
    "Principal",
    "Teacher",
    "Academic Coordinator",
    "Student Success Manager",
    "Admissions Manager",
    "Marketing Manager (Education)",
    "Student Counselor",
    "Training Coordinator",
    "Subject Matter Expert (SME)",
    "Program Manager",
    "Store Manager",
    "Sales Associate",
    "Cashier",
    "Visual Merchandiser",
    "Stock Clerk",
    "Assistant Store Manager",
    "Customer Service Representative",
    "Department Manager",
    "Inventory Manager",
    "Area Manager",
    "Retail Supervisor",
    "Store Director",
    "Product Specialist",
    "Retail Buyer",
    "Operations Manager",
    "Sales Manager",
    "E-commerce Manager",
    "Marketing Manager",
    "Human Resources Manager",
    "Regional Manager",
    "Director",
    "Manager",
    "Assistant Manager",
    "Deputy Manager",
    "General Manager",
    "Senior Manager",
    "Chief Executive Officer (CEO)",
    "Chief Financial Officer (CFO)",
    "Deputy General Manager",
    "Executive Director",
    "Officer",
    "Assistant Officer",
    "Consultant",
    "Head of Department",
    "Senior Executive",
    "Joint Secretary",
    "Under Secretary",
    "Deputy Secretary",
    "Assistant Secretary",
    "Section Officer",
    "General Manager",
    "Hotel Manager",
    "Assistant Manager",
    "Front Office Manager",
    "Housekeeping Manager",
    "Food and Beverage Manager",
    "Sales and Marketing Manager",
    "Revenue Manager",
    "Human Resources Manager",
    "Executive Chef",
    "Sous Chef",
    "Concierge",
    "Event Coordinator",
    "Guest Relations Manager",
    "Reservation Manager",
    "Operations Manager",
    "Duty Manager",
    "Guest Services Associate",
    "Maintenance Manager",
    "Bartender",
    "Waitstaff",
    "Valet",
    "Bellhop",
    "Security Manager",
    "Spa Manager",
    "Restaurant Manager",
    "Front Desk Agent",
    "Food Runner",
    "Room Attendant",
    "Housekeeping Staff",
    "CEO (Chief Executive Officer)",
    "COO (Chief Operating Officer)",
    "CTO (Chief Technology Officer)",
    "CMO (Chief Marketing Officer)",
    "Creative Director",
    "Content Manager",
    "Production Manager",
    "Editor",
    "Art Director",
    "Senior Writer",
    "Scriptwriter",
    "Director of Photography",
    "Sound Designer",
    "Visual Effects Supervisor",
    "Marketing Manager",
    "Public Relations Manager",
    "Social Media Manager",
    "Talent Manager",
    "Cinematographer",
    "Graphic Designer",
    "Video Editor",
    "Media Planner",
    "Brand Manager",
    "Digital Marketing Manager",
    "Distribution Manager",
    "Attorney",
    "Partner",
    "Associate",
    "Counsel",
    "General Counsel",
    "Managing Partner",
    "Senior Associate",
    "Junior Associate",
    "Paralegal",
    "Legal Secretary",
    "Legal Assistant",
    "Compliance Officer",
    "Litigation Support",
    "Corporate Counsel",
    "Contracts Manager",
    "Network Engineer",
    "Telecommunications Technician",
    "Project Manager",
    "Sales Manager",
    "Customer Support Executive",
    "Business Development Manager",
    "System Administrator",
    "Technical Support Specialist",
    "Field Service Engineer",
    "Product Manager",
    "Software Engineer",
    "Data Analyst",
    "Network Architect",
    "Operations Manager",
    "Account Manager",
    "Supply Chain Manager",
    "Logistics Manager",
    "Warehouse Manager",
    "Inventory Control Manager",
    "Procurement Manager",
    "Transportation Manager",
    "Operations Manager",
    "Distribution Manager",
    "Supply Chain Analyst",
    "Logistics Coordinator",
    "Fleet Manager",
    "Shipping Manager",
    "Supply Chain Planner",
    "Import/Export Manager",
    "Freight Forwarding Specialist",
    "Customs Compliance Manager",
    "Order Fulfillment Manager",
    "Sourcing Manager",
    "Demand Planner",
    "Inventory Analyst",
    "Electrical Engineer",
    "Project Manager",
    "Safety Officer",
    "Farm Manager ",
    "Agronomist",
    "Horticulturist",
    "Soil Scientist ",
    "Livestock Manager",
    "Plant Pathologist",
    "Agricultural Engineer",
    "Farm Labor Supervisor",
    "Crop Consultant",
    "Irrigation Specialist",
    "Agricultural Economist",
    "Agricultural Sales Representative",
    "Food Safety Manager",
    "Research Scientist (Agriculture)",
    "Supply Chain Manager ",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Software Engineer",
    "Project Engineer",
    "Design Engineer",
    "Quality Assurance Engineer",
    "Structural Engineer",
    "Systems Engineer",
    "Environmental Engineer",
    "Manufacturing Engineer",
    "Industrial Engineer",
    "Process Engineer",
    "Construction Manager",
    "Maintenance Engineer",
    "Site Engineer",
    "Project Manager",
    "Engineering Manager",
    "Pharmacist",
    "Pharmaceutical Sales Representative",
    "Regulatory Affairs Specialist",
    "Clinical Research Associate (CRA)",
    "Formulation Scientist",
    "Quality Control Analyst",
    "Quality Assurance Manager",
    "Medical Affairs Manager",
    "Research and Development (R&D) Scientist",
    "Pharmacovigilance Officer",
    "Manufacturing Technician",
    "Product Development Specialist",
    "Clinical Trial Manager",
    "Supply Chain Manager",
    "Biotech Engineer",
    "Drug Safety Officer",
    "Market Access Manager",
    "Regulatory Affairs Manager",
    "Construction & Project Management:",
    "Project Manager",
    "Site Manager",
    "Construction Manager",
    "Estimator",
    "Quantity Surveyor",
    "Site Supervisor",
    "Construction Engineer",
    "Safety Officer",
    "Foreman",
    "Architect",
    "Civil Engineer",
    "MEP Engineer (Mechanical, Electrical, Plumbing)",
    "Real Estate:",
    "Real Estate Manager",
    "Property Manager",
    "Real Estate Analyst",
    "Sales Manager",
    "Leasing Consultant",
    "Investment Analyst",
    "Development Manager",
    "Construction Estimator",
    "Facilities Manager",
    "Support & Administration:",
    "HR Manager",
    "Office Administrator",
    "Procurement Manager",
    "Contract Manager",
    "Finance Manager",
    "Marketing Manager",
    "Legal Counsel",
    "Engineering and Design:",
    "Automotive Engineer",
    "Mechanical Engineer",
    "Product Design Engineer",
    "Vehicle Dynamics Engineer",
    "Design Manager",
    "CAD Engineer (Computer-Aided Design)",
    "Manufacturing and Production:",
    "Production Manager",
    "Plant Supervisor",
    "Quality Control Engineer",
    "Assembly Line Worker",
    "Process Engineer",
    "Manufacturing Technician",
    "Sales and Marketing:",
    "Sales Manager",
    "Marketing Manager",
    "Business Development Manager",
    "Brand Manager",
    "Dealer Sales Executive",
    "Supply Chain and Logistics:",
    "Supply Chain Manager",
    "Logistics Coordinator",
    "Procurement Specialist",
    "Warehouse Supervisor",
    "Research and Development (R&D):",
    "R&D Engineer",
    "Test Engineer",
    "Innovation Manager",
    "Vehicle Testing Engineer",
    "After-Sales and Service:",
    "Service Manager",
    "Customer Support Specialist",
    "Technical Support Engineer",
    "Service Technician",
    "Administrative and Support:",
    "Human Resources Manager",
    "Finance Manager",
    "IT Specialist",
    "Administrative Assistant",
    "Executive and Leadership:",
    "Chief Executive Officer (CEO)",
    "Chief Operating Officer (COO)",
    "General Manager",
    "Vice President of Operations",
    "Tourism Manager",
    "Tour Guide",
    "Travel Consultant",
    "Destination Manager",
    "Tour Operations Manager",
    "Customer Service Representative",
    "Travel Coordinator",
    "Event Planner",
    "Sales Manager (Tourism)",
    "Hotel and Resort Manager",
    "Marketing and Communications Manager",
    "Reservation Specialist",
    "Tourism Development Officer",
    "Sustainability Coordinator (Tourism)",
    "Travel Agency Director",
    "Product Development Manager (Tourism)",
    "Airline Partnership Manager",
    "Event Manager",
    "Event Planner",
    "Event Coordinator",
    "Event Producer",
    "Venue Manager ",
    "Marketing Manager (Events)",
    "Sponsorship Manager",
    "Logistics Manager",
    "Creative Director (Events)",
    "Technical Director",
    "Aerospace Engineer",
    "Systems Engineer",
    "Avionics Technician",
    "Defense Analyst",
    "Manufacturing Engineer",
    "Test Engineer",
    "Flight Test Engineer",
    "Project Manager",
    "Quality Assurance Engineer",
    "Program Manager",
    "Embedded Systems Engineer",
    "Materials Engineer",
    "Software Engineer",
    "Structural Engineer",
    "Mechanical Engineer",
    "Supply Chain Manager",
    "Security Specialist",
    "Logistics Coordinator",
    "Cybersecurity Analyst",
    "Compliance Officer",
    "1. Marketing & Sales",
    "Brand Manager",
    "Sales Manager",
    "Area Sales Manager",
    "Regional Sales Manager",
    "Marketing Executive",
    "Trade Marketing Manager",
    "Digital Marketing Manager",
    "Product Manager",
    "Key Account Manager",
    "2. Supply Chain & Logistics",
    "Supply Chain Manager",
    "Logistics Manager",
    "Distribution Manager",
    "Warehouse Manager",
    "Procurement Manager",
    "3. Operations & Manufacturing",
    "Operations Manager",
    "Production Manager",
    "Plant Manager",
    "Factory Supervisor",
    "Process Improvement Manager",
    "4. Finance & Accounting",
    "Finance Manager",
    "Financial Analyst",
    "Cost Accountant",
    "Internal Auditor",
    "5. Human Resources",
    "HR Manager",
    "Recruitment Manager",
    "Training and Development Manager",
    "Employee Relations Manager",
    "6. Quality Assurance & R&D",
    "Quality Assurance Manager",
    "R&D Manager",
    "Regulatory Affairs Manager",
    "Textile Designer",
    "Apparel Designer",
    "Production Manager",
    "Quality Control Manager",
    "Merchandiser",
    "Supply Chain Manager",
    "Fabric Technologist",
    "Pattern Maker",
    "Garment Technologist",
    "Production Planner",
    "Fabric Sourcing Manager",
    "Dyeing Technician",
    "Sales Manager",
    "Marketing Manager",
    "Textile Engineer",
    "Project Manager",
    "Civil Engineer",
    "Structural Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Site Supervisor",
    "Construction Manager",
    "Quantity Surveyor",
    "Safety Officer",
    "Architect",
    "Design Engineer",
    "Project Coordinator",
    "Estimator",
    "BIM Manager (Building Information Modeling)",
    "Planning Engineer",
    "Site Engineer",
    "MEP Engineer (Mechanical, Electrical, Plumbing)",
    "Foreman",
    "Contract Manager",
    "Field Engineer",
    "Leisure Manager",
    "Event Coordinator",
    "Recreation Director",
    "Guest Relations Manager",
    "Activities Supervisor",
    "Entertainment Director",
    "Resort Manager",
    "Marketing Coordinator",
    "Spa Manager",
    "Sales Executive",
    "Executive Director",
    "Program Manager",
    "Project Coordinator",
    "Fundraising Manager",
    "Grant Writer",
    "Monitoring and Evaluation Specialist",
    "Communications Officer",
    "Advocacy Coordinator",
    "Finance Manager",
    "Community Outreach Specialist",
    "Volunteer Coordinator",
    "Research Analyst",
    "HR Manager",
    "Partnerships Manager"
  ];
}
